version: '3.8'

services:

  snipe-mysql:
    container_name: snipe-mysql
    image: mysql:5.6
    env_file:
      - ./snipe_env
    volumes:
      - snipesql-vol:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    restart:
      always

  snipe-it:
    image: snipe/snipe-it
    env_file:
      - ./snipe_env
    ports:
      - "8080:80"
    depends_on:
      - snipe-mysql
    restart:
      always

volumes:
  snipesql-vol:

