spring:
  ## APPLICATION NAME
  application:
    name: asset-management
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  ## MAILING CONFIGURATION
  mail:
    host: smtp.gmail.com
    password: caytmymzlhuzlisg
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender: HAYTHAM DAHRI
    username: haytham.dahri@gmail.com
  mvc:
    dispatch-options-request: true
    ## STATIC RESOURCES LOCATION PATH
    static-path-pattern: /static/**
  servlet:
    ## MULTIPART (MULTIPART PROPERTIES)
    multipart:
      # ========= Enable multipart uploads =========
      enabled: true
      # ========= Threshold after which files are written to disk. =========
      file-size-threshold: 2KB
      # ========= Max file size. =========
      max-file-size: 200MB
      # ========= Max Request Size =========
      max-request-size: 215MB
  ## MONGODB CONFIGURATION
  data:
    mongodb:
      database: ${MONGO_DB:assetmanagement}
      uri: ${MONGO_URI:mongodb://root:toortoor@cluster0-shard-00-00.gkcjl.mongodb.net:27017,cluster0-shard-00-01.gkcjl.mongodb.net:27017,cluster0-shard-00-02.gkcjl.mongodb.net:27017/assetmanagement?ssl=true&replicaSet=atlas-ziuppa-shard-0&authSource=admin&retryWrites=true&w=majority}


## JWT CONFIGURATION
jwt:
  secret: topsecretjwt

## ACTIVATION TOKEN EXPIRATION DURATION
token:
  expiration: 216000

## SERVER PORT
server:
  port: ${PORT:8080}

## UPLOAD DIRECTORY
files:
  upload-directory: ${user.home}/AssetManagementFiles

## HOSTNAME
HOSTNAME: http://localhost

## PAGINATION CONFIGURATION
page:
  default-size: 20

## RECAPTCHA KEY
google:
  recaptcha:
    url: https://www.google.com/recaptcha/api/siteverify
    secret-key: 6Lfit74ZAAAAAICcWlmd69FZRT8r_18O7VG4UrpA
    site-key: 6Lfit74ZAAAAALJMmqIj1gI5h-CS0-dKhKwildCr
