package org.management.asset.entities;

/**
 * @author Haytam DAHRI
 */
public enum RoleType {

    ROLE_SUPER_USER,

    ROLE_ADMIN,

    ROLE_CSV_IMPORT,

    ROLE_REPORTS_VIEW,

    ROLE_ASSETS_VIEW,
    ROLE_ASSETS_CREATE,
    ROLE_ASSETS_EDIT,
    ROLE_ASSETS_DELETE,
    ROLE_ASSETS_CHECKIN,
    ROLE_ASSETS_CHECKOUT,
    ROLE_ASSETS_AUDIT,
    ROLE_ASSETS_VIEW_REQUESTABLE_ASSETS,

    ROLE_ACCESSORIES_VIEW,
    ROLE_ACCESSORIES_CREATE,
    ROLE_ACCESSORIES_EDIT,
    ROLE_ACCESSORIES_DELETE,
    ROLE_ACCESSORIES_CHECKOUT,
    ROLE_ACCESSORIES_CHECKIN,

    ROLE_CONSUMABLE_VIEW,
    ROLE_CONSUMABLE_CREATE,
    ROLE_CONSUMABLE_EDIT,
    ROLE_CONSUMABLE_DELETE,
    ROLE_CONSUMABLE_CHECKOUT,

    ROLE_LICENSES_VIEW,
    ROLE_LICENSES_CREATE,
    ROLE_LICENSES_EDIT,
    ROLE_LICENSES_DELETE,
    ROLE_LICENSES_CHECKOUT,
    ROLE_LICENSES_VIEW_LICENSE_KEYS,

    ROLE_COMPONENTS_VIEW,
    ROLE_COMPONENTS_CREATE,
    ROLE_COMPONENTS_EDIT,
    ROLE_COMPONENTS_DELETE,
    ROLE_COMPONENTS_CHECKOUT,
    ROLE_COMPONENTS_CHECKIN,

    ROLE_USERS_VIEW,
    ROLE_USERS_CREATE_USERS,
    ROLE_USERS_EDIT_USERS,
    ROLE_USERS_DELETE_USERS,

    ROLE_MODELS_VIEW,
    ROLE_MODELS_CREATE,
    ROLE_MODELS_EDIT,
    ROLE_MODELS_DELETE,

    ROLE_CATEGORIES_VIEW,
    ROLE_CATEGORIES_CREATE,
    ROLE_CATEGORIES_EDIT,
    ROLE_CATEGORIES_DELETE,

    ROLE_DEPARTMENTS_VIEW,
    ROLE_DEPARTMENTS_CREATE,
    ROLE_DEPARTMENTS_EDIT,
    ROLE_DEPARTMENTS_DELETE,

    ROLE_STATUS_LABELS_VIEW,
    ROLE_STATUS_LABELS_CREATE,
    ROLE_STATUS_LABELS_EDIT,
    ROLE_STATUS_LABELS_DELETE,

    ROLE_SUPPLIERS_VIEW,
    ROLE_SUPPLIERS_CREATE,
    ROLE_SUPPLIERS_EDIT,
    ROLE_SUPPLIERS_DELETE,

    ROLE_MANUFACTURERS_VIEW,
    ROLE_MANUFACTURERS_CREATE,
    ROLE_MANUFACTURERS_EDIT,
    ROLE_MANUFACTURERS_DELETE,

    ROLE_DEPRECIATIONS_VIEW,
    ROLE_DEPRECIATIONS_CREATE,
    ROLE_DEPRECIATIONS_EDIT,
    ROLE_DEPRECIATIONS_DELETE,

    ROLE_LOCATIONS_VIEW,
    ROLE_LOCATIONS_CREATE,
    ROLE_LOCATIONS_EDIT,
    ROLE_LOCATIONS_DELETE,

    ROLE_COMPANIES_VIEW,
    ROLE_COMPANIES_CREATE,
    ROLE_COMPANIES_EDIT,
    ROLE_COMPANIES_DELETE
}
