package org.management.asset.bo;

/**
 * @author Haytam DAHRI
 */
public enum RoleType {

    ROLE_SUPER_USER,

    ROLE_ADMIN,

    ROLE_CSV_IMPORT,

    ROLE_REPORTS_VIEW,

    ROLE_ASSETS_VIEW,
    ROLE_ASSETS_CREATE,
    ROLE_ASSETS_EDIT,
    ROLE_ASSETS_DELETE,
    ROLE_ASSETS_CHECKIN,
    ROLE_ASSETS_CHECKOUT,
    ROLE_ASSETS_AUDIT,
    ROLE_ASSETS_VIEW_REQUESTABLE_ASSETS,

    ROLE_ACCESSORIES_VIEW,
    ROLE_ACCESSORIES_CREATE,
    ROLE_ACCESSORIES_EDIT,
    ROLE_ACCESSORIES_DELETE,
    ROLE_ACCESSORIES_CHECKOUT,
    ROLE_ACCESSORIES_CHECKIN,

    ROLE_RISKANALYZES_VIEW,
    ROLE_RISKANALYZES_CREATE,
    ROLE_RISKANALYZES_EDIT,
    ROLE_RISKANALYZES_DELETE,
    ROLE_RISKANALYZES_CHECKOUT,

    ROLE_LICENSES_VIEW,
    ROLE_LICENSES_CREATE,
    ROLE_LICENSES_EDIT,
    ROLE_LICENSES_DELETE,
    ROLE_LICENSES_CHECKOUT,
    ROLE_LICENSES_VIEW_LICENSE_KEYS,

    ROLE_ENTITIES_VIEW,
    ROLE_ENTITIES_CREATE,
    ROLE_ENTITIES_EDIT,
    ROLE_ENTITIES_DELETE,

    ROLE_USERS_VIEW,
    ROLE_USERS_CREATE_USERS,
    ROLE_USERS_EDIT_USERS,
    ROLE_USERS_DELETE_USERS,

    ROLE_TYPOLOGIES_VIEW,
    ROLE_TYPOLOGIES_CREATE,
    ROLE_TYPOLOGIES_EDIT,
    ROLE_TYPOLOGIES_DELETE,

    ROLE_THREATS_VIEW,
    ROLE_THREATS_CREATE,
    ROLE_THREATS_EDIT,
    ROLE_THREATS_DELETE,

    ROLE_DEPARTMENTS_VIEW,
    ROLE_DEPARTMENTS_CREATE,
    ROLE_DEPARTMENTS_EDIT,
    ROLE_DEPARTMENTS_DELETE,

    ROLE_STATUS_LABELS_VIEW,
    ROLE_STATUS_LABELS_CREATE,
    ROLE_STATUS_LABELS_EDIT,
    ROLE_STATUS_LABELS_DELETE,

    ROLE_PROCESSES_VIEW,
    ROLE_PROCESSES_CREATE,
    ROLE_PROCESSES_EDIT,
    ROLE_PROCESSES_DELETE,

    ROLE_RISKSCENARIOS_VIEW,
    ROLE_RISKSCENARIOS_CREATE,
    ROLE_RISKSCENARIOS_EDIT,
    ROLE_RISKSCENARIOS_DELETE,

    ROLE_VULNERABILITIES_VIEW,
    ROLE_VULNERABILITIES_CREATE,
    ROLE_VULNERABILITIES_EDIT,
    ROLE_VULNERABILITIES_DELETE,

    ROLE_LOCATIONS_VIEW,
    ROLE_LOCATIONS_CREATE,
    ROLE_LOCATIONS_EDIT,
    ROLE_LOCATIONS_DELETE,

    ROLE_ORGANIZATIONS_VIEW,
    ROLE_ORGANIZATIONS_CREATE,
    ROLE_ORGANIZATIONS_EDIT,
    ROLE_ORGANIZATIONS_DELETE
}
